name: Deploy to AKS

on:
  push:
    paths:
      - 'deployment.yaml'
      - 'hpa.yaml'
      - 'service.yaml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: |
          KUBECONFIG=$HOME/.kube/config kubectl apply -f deployment.yaml --validate=false
  	  KUBECONFIG=$HOME/.kube/config kubectl apply -f hpa.yaml --validate=false
  	  KUBECONFIG=$HOME/.kube/config kubectl apply -f service.yaml --validate=false
